projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v

app_name = 'produto'

urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('categoria/', v.ProdutoCategoriaCreate.as_view(), name='produto_categoria'),
    path('<int:pk>/json/', v.produto_json, name='produto_json'),
    path('import/csv/', v.import_csv, name='import_csv'),
    path('export/csv/', v.export_csv, name='export_csv'),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
]

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy

class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NMC', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('Preço', max_digits=11, decimal_places=2)
    estoque = models.IntegerField('Estoque_atual')
    estoque_minimo = models.PositiveIntegerField('Estoque mínimo', default=0)
    categoria = models.ForeignKey(
            'Categoria',
            on_delete=models.SET_NULL,
            null=True,
            blank=True
            )

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk':self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }


class Categoria(models.Model):
    categoria = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ('categoria',)

    def __str__(self):
        return self.categoria

projeto/produto/forms.py
from django import forms
from .models import Produto, Categoria

class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'


class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = '__all__'

projeto/produto/views.py
import csv
import io
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.views.generic import CreateView, UpdateView, ListView
from .models import Produto, Categoria
from .forms import ProdutoForm, CategoriaForm

def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    search = request.GET.get('search')
    if search:
        objects = objects.filter(produto__icontains=search)
    context = {'object_list':objects}
    return render(request, template_name, context)


class ProdutoList(ListView):
    model = Produto
    template_name = 'produto_list.html'
    paginate_by = 8

    def get_queryset(self): # new
        search = self.request.GET.get('search')
        if search:
            object_list = Produto.objects.filter(produto__icontains=search)
        else:
            object_list = Produto.objects.all()

        return object_list



def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object':obj}
    return render(request, template_name, context)

def produto_add(request):
    template_name = 'produto_form.html'
    return render(request, template_name)

class ProdutoCategoriaCreate(CreateView):
    model = Categoria
    template_name='produto_categoria_form.html'
    form_class = CategoriaForm

class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm

class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    """ Retorna o produto, id e o estoque """
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})


def save_data(data):
    '''
    Salva os dados no banco.
    '''
    aux = []
    for item in data:
        produto = item.get('produto')
        ncm = str(item.get('ncm'))
        importado = True if item.get('importado') == 'True' else False
        preco = item.get('preco')
        estoque = item.get('estoque')
        estoque_minimo = item.get('estoque_minimo')
        obj = Produto(
            produto=produto,
            ncm=ncm,
            importado=importado,
            preco=preco,
            estoque=estoque,
            estoque_minimo=estoque_minimo,
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)


@login_required
def import_csv(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        # Lendo arquivo InMemoryUploadedFile
        file = myfile.read().decode('utf-8')
        reader = csv.DictReader(io.StringIO(file))
        # Gerando uma list-comprehension
        data = [line for line in reader]
        save_data(data)
        return HttpResponseRedirect(reverse('produto:produto_list'))
    template_name = 'produto_import.html'
    return render(request, template_name)


@login_required
def export_csv(request):
    header = (
        'importado',
        'ncm',
        'produto',
        'preco',
        'estoque',
        'estoque_minimo',
    )
    produtos = Produto.objects.all().values_list(*header)
    with open('fix/produtos_exportado.csv', 'w') as csvfile:
        produto_writer=csv.writer(csvfile)
        produto_writer.writerow(header)
        for produto in produtos:
            produto_writer.writerow(produto)
    messages.success(request, 'Produtos exportados com sucesso!')
    return HttpResponseRedirect(reverse('produto:produto_list'))

projeto/produto/templates/produto_categoria_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <style>
        span.required:after {
            content: " *";
            color: red;
        }
    </style>
{% endblock css %}

{% block content %}

<div class="page-header">
    <h2><i class="fa fa-user">  Categoria de Produtos</i></h2>
</div>

<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
            {% if field.field.required %}
                <span class="required">{{field.label}}</span>
            {% else %}
                {{ field.label }}
            {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
    <span class="pull-right">
        <a href="{% url 'produto:produto_list' %}" class="btn btn-primary">Voltar</a>
    </span>
</form>

{% endblock %}

{% block js %}
    <script src="{% static 'js/produto.js' %}"></script>
{% endblock js %}

projeto/produto/templates/produto_detail.html
{% extends 'base.html' %}

{% block content %}

<span class="pull-right">
    <a href="{% url 'produto:produto_list' %}" class="btn btn-primary">Voltar</a>
    <a href="{% url 'produto:produto_edit' object.pk %}">
    <button type="button" class="btn btn-success">Editar
        <span class="fa fa-pencil"></span>
    </button>
    </a>
    </span>
<h1 class="text-left" style="margin-top: 80px;margin-bottom: 18px;">
    <span class="alert alert-info">
        {{ object }}
    </span>
</h1>
<div class="col-sm-6">
<table class="table table-user-information">
    <tbody>
        <tr>
            <th class="text-right">Importado</th>
            <td>
                {% if object.importado %}
                    <i class="fa fa-check-circle ok"></i>
                {% else %}
                    <i class="fa fa-minus-circle no"></i>
                {% endif %}
            </td>
        </tr>
        <tr>
            <th class="text-right">Produto</th>
            <td>{{object.produto}}</td>
        </tr>
        <tr>
            <th class="text-right">NCM</th>
            <td>{{object.ncm}}</td>
        </tr>
        <tr>
            <th class="text-right">Preço</th>
            <td>R$ {{object.preco}}</td>
        </tr>
        <tr>
            <th class="text-right">Estoque</th>
            <td>{{object.estoque}}</td>
        </tr>
        <tr>
            <th class="text-right">Estoque mínimo</th>
            <td>{{object.estoque_minimo}}</td>
        </tr>
    </tbody>
</table>
</div>

{% endblock content %}

projeto/produto/templates/produto_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <style>
        span.required:after {
            content: " *";
            color: red;
        }
    </style>
{% endblock css %}

{% block content %}

<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
            {% if field.field.required %}
                <span class="required">{{field.label}}</span>
            {% else %}
                {{ field.label }}
            {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
    <span class="pull-right">
        <a href="{% url 'produto:produto_list' %}" class="btn btn-primary">Voltar</a>
    </span>
</form>

{% endblock %}

{% block js %}
    <script src="{% static 'js/produto.js' %}"></script>
{% endblock js %}

projeto/produto/templates/produto_import.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <style>
        span.required:after {
            content: " *";
            color: red;
        }
    </style>
{% endblock css %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input name="myfile" class="form-control" type="file"/>
    <button type="submit" class="btn btn-success">Importar</button>
    <span class="pull-right">
        <a href="{% url 'produto:produto_list' %}" class="btn btn-primary">Voltar</a>
    </span>
</form>

{% endblock %}

projeto/produto/templates/produto_list.html
{% extends 'base.html' %}

{% block css %}

{% endblock css %}

{% block content %}

{% for message in messages %}
    {% if 'success' in messages.tag %}
	<p class="alert alert-success" role="alert">
	   <span style="font-weight: bold;">{{ message }}</span>
	</p>
    {% else %}
	<p class="alert alert-success" role="alert">
	   <span style="font-weight: bold;">{{ message }}</span>
	</p>
    {% endif %}
{% endfor %}

<div class="page-header">
    <h2><i class="fa fa-user">  Lista de Produtos</i></h2>
</div>
<form action="." method="GET">
        <div class="row">
            <div class="col-sm-6">
                <input name="search" class="form-control" type="text" placeholder="Buscar..." value="{{request.GET.search}}">
            </div>
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i> Pesquisar
                </button>
                <a href="{% url 'produto:produto_list' %}">
                    <button type="button" class="btn btn-primary" style="margin-left: 5px">
                        <i class="fa fa-minus"></i> Limpar
                    </button>
                </a>
        </div>
    </form>
<span class="pull-right" style="margin-left: 10px">
    <a href="{% url 'produto:produto_categoria' %}">
        <button type="button" class="btn btn-primary">
            <span class="fa fa-book"></span> Categoria
        </button>
    </a>
</span>
<span class="pull-right" style="margin-left: 10px">
    <a href="{% url 'produto:produto_add' %}">
        <button type="button" class="btn btn-primary">
            <span class="fa fa-plus"></span> Adicionar
        </button>
    </a>
</span>


{% if object_list %}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Importado</th>
            <th>NCM</th>
            <th>Produto</th>
	    <th>Categoria</th>
	    <th>Preço</th>
            <th class="text-center">Estoque</th>
            <th class="text-center">Estoque mínimo</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>
                {% if object.importado %}
                    <i class="fa fa-check-circle ok"></i>
                {% else %}
                    <i class="fa fa-minus-circle no"></i>
                {% endif %}
            </td>
            <td>{{object.ncm}}</td>
            <td>
                <a href="{{ object.get_absolute_url }}">
                    {{object.produto}}
                </a>
            </td>
	    <td>
                <a href="{{ object.get_absolute_url }}">
                    {{object.categoria}}
                </a>
            </td>
            <td>
                R$ <span class="pull-right">
                    {{object.preco}}
                </span>
            </td>
            <td class="text-center">{{object.estoque}}</td>
            <td class="text-center">{{object.estoque_minimo}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

{% include "includes/pagination.html" %}

{% endblock content %}

{% block js %}
<script>
// Close alerts after 2 seconds
window.setTimeout(function() {
    $('.alert').fadeTo(500,0).slideUp(500, function() {
    	$(this).remove();
    });
}, 2000);
</script>
{% endblock js %}